### ISSUE TITLE
Default tab could not be found

### ISSUE THREAD

**Issue by kishandhanak** [JangoSteve/jQuery-EasyTabs#153]
Hi,

Im using your easy tabs plugin on WordPress and have found that I'm getting the following jquery error:

Uncaught Error: The specified default tab ('li:first-child') could not be found in the tab set ('> ul > li') out of 0 tabs.

I'm using WordPress 3.8 with jquery.js?ver=1.10.2. I'm also using the plugin out of the box as per your instructions.

Could you kindly advise.

Thank you very much in advance,

**Comment by rene-hermenau** [comment]
This works! Thank you guys :+1:
