### ISSUE TITLE
scroll to top of panel's content when opening new tab - page anchor behaviour

### ISSUE THREAD

**Issue by ghost** [JangoSteve/jQuery-EasyTabs#156]
I have noticed when the panel's height is more than the height of the viewport and the user clicks to open a new tab from the bottom of the current panel's content (through disconnected tabs nav or a fixed tabs nav for example) the new panel's content will load but it will not show the user the content from its top but actually stay on the same height of the previous panel's content. This makes the new panel load in the middle or the bottom of its content, depending on how far down into the content of the previous panel the user was on.

If the loading tab's panel is smaller in height than the previous panel's height the new tab's panel will show the content from the bottom of the new panel, so the user actually has to scroll up to see the top of the content of the new tab.

It would be great if someone can help me figure out how to have the panels load the content of the selected tab and then scroll the top of the viewport to the top of the selected tab's panel so that the user does not need to scroll up from the previous panel's middle or bottom to get to the beginning of the new panel's content.

Looking at how browsers behave with in page anchor links, when clicked the user is directed to the top of the selected page anchor and its following content, scrolling the viewport when necessary. It would be great if EasyTabs could exhibit this same behaviour. I thought about this since considering the new tabs and their panels are in fact or could be seen as page anchor links.

So when the user clicks on a new tab the user's viewport should be directed to the top of the new opening panel's content, no? A variation of this could be having EasyTabs check if the top of the panel's content is visible on the user's viewport, and of not, scroll the viewport up or down from the current location to the start of the loading panel's content.

What do you think?

Looking at this from a usability and or information design perspective it only seems very natural to me to present the user with the beginning of the content the user wished to see through clicking on a link on the page, be this a same page anchor or a tab in this case.

**Comment by mmaithani** [comment]
`$('#wrapper').easytabs({`
`	animate			: true,`
`	updateHash		: true,`
`	transitionIn	:'fadeIn',`
`	transitionOut	:'fadeOut',`
`	animationSpeed	:100,`
`	tabActiveClass	:'active',`
`	tabs            :' #main-nav.tabbed > ul > li ',`
`	transitionInEasing: 'linear',`
 `	transitionOutEasing: 'linear',`	
 `	scrollTop: 0`
`});`

**update hash: true and everything wil work fine**
