### ISSUE TITLE
Page scrolls to top on every tab click

### ISSUE THREAD

**Issue by jonbach** [JangoSteve/jQuery-EasyTabs#197]
EasyTabs works great for me, except for one piece I can't figure out.   If I scroll down on the page slightly, then click on a tab, the page jumps back up to the top.  I've seen other reports were setting min-height in the tab container fixes it, but that did not work here.

See it in action at http://www.pugetsystems.com/parts_beta/Case/Fractal-Design-Define-R4-Titanium-Grey-8803 (scroll down 100-200 pixels or so, then click a tab)

**Comment by jmp909** [comment]
jonbach's solution worked for me in latest chrome. #203 didn't
