### ISSUE TITLE
If tab exisits, if not 

### ISSUE THREAD

**Issue by MobsterGit** [JangoSteve/jQuery-EasyTabs#220]
I'm currently working on a project that requires a conditional to display data if exists, if it doesn't I need to hide the tab.  
Problem is, easytabs is sill looking for default tab and throws an error.  

Error: The specified default tab ('li:first-child') could not be found in the tab set ('> ul > li') out of 0 tabs.

I suppose I need a conditional for the js as well?

**Comment by JangoSteve** [comment]
I'm a little unclear on what the use-case is. It seems like this would only happen if there are zero tabs total in the easytab container. If that's the case though, could you avoid calling easytabs in some way (maybe by only calling it on a selector that exists if there is at least one tab present)?

**Comment by MobsterGit** [comment]
Thanks for the reply.  I think resolved it with a little if statement, if easytabs, do something.  If you want, I'll post it as a follow up in case someone else runs into the issue. 

~Denny

**Comment by JangoSteve** [comment]
Awesome, thanks, that'd be great.

**Comment by MobsterGit** [comment]
Ok, so I resolved this by including it in an "if" conditional to see if it exists before calling .easytabs().  Pretty simple. Thanks! 

```
if ( $( "#tab-container li:first-child" ).length ) {
     $('#tab-container').easytabs(); 
}
```

**Comment by JangoSteve** [comment]
Awesome, sounds good. Thanks for the update, @MobsterGit!
