### ISSUE TITLE
Is this project dropped?

### ISSUE THREAD

**Issue by treyssatvincent** [JangoSteve/jQuery-EasyTabs#233]

**Comment by halfer** [comment]
It's not seen updates for five years, and it's only available through Bower, which is now deprecated. So, that's probably your answer: yes.

I'm still using it though.

**Comment by X25guru** [comment]
var fire = function(obj, name, data) {
      var event = $.Event(name);
      obj.trigger(event, data);
      return event.result !== false;
    };

this line needs a semi at the end; my packer function didn't like it. FYI

**Comment by halfer** [comment]
@X25guru: you should probably open a new ticket about that (although, since it is not maintained, it is not likely to get done).

**Comment by treyssatvincent** [comment]
I'm closing this issue, it seems clear that it's not maintained.

I've forked it to implement #232 and removed a lot of code, I don't maintain it actively but I can review and merge pull requests : https://github.com/treyssatvincent/jQuery-AjaxTabs.
