### ISSUE TITLE
Scrolling Problem

### ISSUE THREAD

**Issue by cmyharish** [JangoSteve/jQuery-EasyTabs#40]
Hi the Script is supered and very easy to customize, but i am facing one small issue.

When i click on the tab link, browser moves to top, how to solve this, please help.

Regards
Harish

**Comment by morenopc** [comment]
It took some time but finally found an answer that worked for me:

``` javascript
$('#tabs').easytabs({animationSpeed: 'fast', updateHash: false});
```

at http://stackoverflow.com/a/27676546/1271868

p.s. sorry to resurrect an old post but I'm running the newest version and none of the answers above worked for me.
